from: markdown+emoji
output-file: main.pdf
input-files:
  - main.md
  - includes/references.tex
filters: 
  - pandoc-citeproc
bibliography: references/references.bib
csl: config/apa-6th-edition.csl
pdf-engine: xelatex
include-in-header: includes/in-header.tex
include-before-body: includes/before-body.tex
template: config/template.tex
